default_context:
  project_name: 'movieproject'
  project_slug: 'movies'
  domain_main: 'movies.com'
  domain_staging: 'stag.movies.com'
  docker_swarm_stack_name_main: 'movies-com'
  docker_swarm_stack_name_staging: 'stag-movies-com'
  secret_key: 'dfghjkljhgfdghjkljhgfdhjk'
  first_superuser: 'admin@movies.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.movies.com", "https://stag.movies.com", "https://movies.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@movies.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@movies.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'movies.com'
  traefik_constraint_tag_staging: 'stag.movies.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
